# Generated by Django 5.2.8 on 2025-11-22 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='code_snippet',
            new_name='ai_improved',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='code_summary',
            new_name='ai_summary',
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('question', 'Question'), ('project', 'Project'), ('bug', 'Bug'), ('information', 'Information')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='phone number must contain only digits and can start with +.', regex='^\\+?\\d{6,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='user name must start with letter or _ only, no spaces or special characters, length between 3 and 30.', regex='^[A-Za-z_][A-Za-z0-9_]{2,29}$')]),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
