# Generated by Django 5.2.8 on 2025-11-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
