# Generated by Django 5.2.8 on 2025-11-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_notification_notification_type_aitask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('question', 'Question'), ('project', 'Project'), ('bug', 'Bug'), ('information', 'Information'), ('artical', 'Artical')], max_length=20, null=True),
        ),
    ]
