# Generated by Django 5.2.8 on 2025-11-27 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_commentreaction_delete_commentuseful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='app.comment'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
