# Generated by Django 5.2.8 on 2025-11-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_commentreaction_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('question', 'Question'), ('project', 'Project'), ('problem', 'Problem'), ('information', 'Information'), ('artical', 'Artical')], max_length=20, null=True),
        ),
    ]
