# Generated by Django 5.2.8 on 2025-12-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_user_created_at_remove_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
