# Generated by Django 5.2.8 on 2025-12-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_user_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ai_summary',
            new_name='ai_code_summary',
        ),
    ]
