# Generated by Django 5.2.8 on 2025-12-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_ai_summary_post_ai_code_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
