# Generated by Django 5.2.8 on 2025-12-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_aitask_post_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aitask',
            name='app_aitask_post_id_31b4a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='aitask',
            name='app_aitask_user_id_5c25ae_idx',
        ),
        migrations.AlterField(
            model_name='aitask',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tasks', to='app.post'),
        ),
    ]
