# Generated by Django 5.2.8 on 2025-12-19 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_aitask_app_aitask_post_id_31b4a0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitask',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to='app.post'),
        ),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['post'], name='app_aitask_post_id_31b4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['user', 'status'], name='app_aitask_user_id_5c25ae_idx'),
        ),
    ]
