# Generated by Django 5.2.8 on 2026-01-24 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_aitask_post_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('people', 'People'), ('posts', 'Posts'), ('tag', 'Tag')], max_length=20)),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content'], name='app_post_content_94fae1_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['tags'], name='app_post_tags_dc4f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='app_user_usernam_f7396d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['specialization'], name='app_user_special_7bd41f_idx'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'search_type'], name='app_searchh_user_id_48f5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['query'], name='app_searchh_query_8063d7_idx'),
        ),
    ]
