# Generated by Django 5.2.8 on 2026-01-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_searchhistory_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
