# Generated by Django 5.2.8 on 2026-01-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_searchhistory_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together={('user', 'search_type', 'query')},
        ),
    ]
