# Generated by Django 5.2.8 on 2026-01-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_searchhistory_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
