# Generated by Django 5.2.8 on 2026-01-27 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_delete_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('people', 'People'), ('posts', 'Posts'), ('tag', 'Tag')], max_length=20)),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'search_type'], name='app_searchh_user_id_48f5a0_idx'), models.Index(fields=['query'], name='app_searchh_query_8063d7_idx')],
                'unique_together': {('user', 'search_type', 'query')},
            },
        ),
    ]
