# Generated by Django 5.2.8 on 2026-01-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
