# Generated by Django 5.2.8 on 2026-01-27 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_searchhistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='searched_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searched_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
