# Generated by Django 5.2.8 on 2026-01-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_searchhistory_searched_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='searched_user',
        ),
    ]
