# Generated by Django 5.2.8 on 2026-01-28 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_searchhistory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='searchhistory',
            name='app_searchh_user_id_48f5a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchhistory',
            name='app_searchh_query_8063d7_idx',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searched_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_type',
            field=models.CharField(choices=[('people', 'People'), ('posts', 'Posts'), ('tag', 'Tag')], max_length=10),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together={('user', 'search_type', 'query'), ('user', 'search_type', 'target_user')},
        ),
    ]
