# Generated by Django 5.2.8 on 2026-01-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_searchhistory_app_searchh_user_id_48f5a0_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
