# Generated by Django 5.2.8 on 2026-01-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_searchhistoryi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchHistoryi',
            new_name='SearchHistory',
        ),
    ]
