# Generated by Django 5.2.8 on 2026-03-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_searchhistoryi_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_generated',
            field=models.TextField(blank=True, null=True),
        ),
    ]
