# Generated by Django 5.2.8 on 2026-03-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_passwordresetcode_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code_language',
            field=models.CharField(blank=True, default='plaintext', max_length=50, null=True),
        ),
    ]
