# Generated by Django 5.2.8 on 2026-03-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_post_code_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
