# Generated by Django 5.2.8 on 2026-03-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_post_code_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ai_code_summary',
        ),
    ]
