# Generated by Django 5.2.8 on 2026-03-29 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_user_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='username must start with letter or _ only, no spaces or special characters, length between 3 and 20.', regex='^[A-Za-z_][A-Za-z0-9_]{2,19}$')]),
        ),
    ]
