# Generated by Django 5.2.8 on 2026-03-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
