# Generated by Django 5.2.8 on 2026-03-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_passwordresetcode_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ai_generated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ai_improved',
        ),
    ]
