# Generated by Django 5.2.8 on 2026-04-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_post_post_type_alter_user_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
