# Generated by Django 5.2.8 on 2026-04-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent', '-created_at'], name='post_parent_created_idx'),
        ),
    ]
