# Generated by Django 5.2.8 on 2026-04-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_comment_post_parent_created_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='commentreaction',
            index=models.Index(fields=['comment', 'reaction_type'], name='comment_reaction_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentreaction',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_user_comment_reaction'),
        ),
    ]
